openapi: 3.0.0
info:
  title: Aders-Zero-API
  description: 'Sistema de gestión para automatización'
  version: 1.0.0
paths:
  /api/test:
    get:
      operationId: de498120df635b6cf0bd8c1e5e1a2741
      responses:
        '200':
          description: OK
